# Generated by Django 6.0.5 on 2026-06-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='collections/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
